apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shoppulse
  namespace: shoppulse
  labels:
    app.kubernetes.io/part-of: shoppulse
  annotations:
    appgw.ingress.azure.io/request-timeout: "30"
spec:
  ingressClassName: azure-application-gateway
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-end
                port:
                  number: 80
