apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shoppulse

resources:
  - namespace.yaml
  - deps/postgres.yaml
  - deps/redis.yaml
  - serviceaccounts.yaml  - secret.yaml
  - api-deployment.yaml
  - api-service.yaml
  - front-end-deployment.yaml
  - front-end-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: shoppulse
  app.kubernetes.io/managed-by: kustomize
